language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm i @angular/cli@6.2.4 -g
  - npm i

script:
  - ng build --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
